server:
    port: 8081
    use-forward-headers: true
    undertow:
        # 指定工作者线程的 I/0 线程数，默认为 2 或者 CPU 的个数
        io-threads: 2
        # 指定工作者线程个数，默认为 I/O 线程个数的 8 倍
        worker-threads: 32
        # buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
        buffer-size: 1024
        # 是否分配的直接内存(NIO直接分配的堆外内存)
        directBuffers: true
    compression:
        enabled: true
        min-response-size: 2048
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
    servlet:
      session:
        tracking-modes: cookie
        cookie:
          http-only: true
spring:
    profiles:
        active: @profileActive@
    devtools:
        enabled: true
    cache:
        type: ehcache
        ehcache:
            config: classpath:ehcache.xml
    http:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    freemarker:
        template-loader-path:
        - classpath:/templates
        - file:${site.location}/storage/templates
        cache: false
        check-template-location: true
        charset: utf-8
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##
            auto_import: /utils.ftl as utils
    flyway:
        enabled: false
        baseline-on-migrate: true
        encoding: UTF-8
        locations: classpath:scripts/migration
shiro:
    web:
        enabled: true
    annotations:
        enabled: false
    loginUrl: /login
    successUrl: /index
    unauthorizedUrl: /error/reject.html
    sessionManager:
        cookie:
            maxAge: 604800
    rememberMeManager:
        cookie:
            maxAge: 604800
logging:
    level:
        org.springframework: WARN
        org.hibernate: WARN

# site.options.theme: [default|classic]
site:
    version: 3.5.0
    location: ${user.dir}
    controls:
        # 注册开关
        register: true
        # 注册开启邮箱验证
        register_email_validate: true
        # 发布文章开关
        post: true
        # 评论开关
        comment: true
    options:
        theme: classic
        site_logo: /dist/images/logo/logo.png
        site_favicon: /dist/images/logo/m.png
        storage_max_width: 800
        storage_limit_size: 2
        editor: markdown
        thumbnail_channel_size: 200x112
        thumbnail_post_size: 360x200
